spring:
  application:
    name: forum
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
